var en = {
  welcome_to_program : "Welcome to BlankOn installation program.",
  installation_finish : "Installation Finish.",
  installation_error_occured : "Installation Error Occured.",
  please_take_look : "Please take a look at installion log : /var/log/blankon-installer.log",
  installation : "Installation",
  please_wait_system_scanned : "Please wait while your sistem is being scanned...",
  please_choose_partition : "Please choose the partition on device below which you would like to install BlankOn into or use advanced partitioning tool for more control.",
  install_partition : "Installation Target",
  installation_summary : "Installation Summary",
  install_summary_info : "This is our installation summary. Please proceed if you're agree. Beyond this point, the installer will make changes to your system and you can't go.",
  personalization : "Personalization",
  please_enter_personalization : "Please enter your personalization preference below...",
  computer_name : "Computer Name",
  full_name : "Your Name",
  username : "Username",
  password : "password",
  repeat_password : "Repeat Password",
  automatically_login : "Automatically login",
  enforced_password : "Enforce strong password",
  enforced_password_requirements : "Your password must contain at least 8 letters, a capital, and a numeric",
  please_fill_required_form : "Please fill all the required form.",
  next : "Next",
  previous : "Previous",
  continue_using_livecd : "Continue using live CD",
  install_blankon : "Install BlankOn",
  exit : "Exit",
  install : "Install",
  reboot : "Reboot",
  timezone : "TimeZone",
  select_drive : "Select drive...",
  cancel : "Cancel",
  apply : "Apply",
  use_as_swap : "use as Swap",
  used : "Used",
  too_small : "Too small",
  free_space : "Free space",
  enter_advanced_mode : "Enter Advanced Mode",
  you_are_choosing : "You are choosing",
  to_be_installed_with : "to bee installed with BlankOn.",
  warning : "WARNING",
  the_selected_partition_will_be_wiped_out : "The selected partition will be wiped out. Swap partition will be created if you don't have one.",
  exit_advanced_mode : "Exit Advanced Mode",
  are_you_sure_exit_advanced_mode : "Are you sure you want to exit Advanced Mode?",
  if_yes_any_step_will_be : "If yes, any step in PartoEdi will be aborted.",
  no : "No",
  yes : "Yes",
  should_one_partition_as_root : "There should be at least one partition setup as root filesystem.",
  partition : "Partition",
  file_system : "File System",
  mount_point : "Mount Point",
  size : "Size",
  new_partition : "New Partition",
  unallocated : "Unallocated",
  format_as_ext4 : "Format as ext4",
  create : "Create",
  delete : "Delete",
  action : "Action",
  use_as_home : "Use as /home",
  will_be_ext4 : "This will be formatted as ext4 filesystem.",
  will_be_swap : "This will be formatted as swap filesystem.",
  new_size : "New size",
  partition_type : "Partition Type",
  target_device : "Target device",
  target_partition : "Target partition",
  your_system_is_ready : "Your sistem is ready. Please continue to reboot into your newly installed system.",
  installing_filesystem : "Installing filesystem",
  mounting_filesystem : "Mounting filesystem",
  mounting_home_filesystem : "Mounting home filesystem",
  copying_filesystem : "Copying filesystem",
  setting_up : "Setting up",
  installing_grub : "Installing GRUB",
  cleaning_up : "Cleaning up",
  create_partition : "Create partition",
  format_partition : "Format Partition",
  partitioning_in_advancedMode : "Partitioning in Advanced Mode",
}

var id = {
  welcome_to_program : "Selamat datang di program pemasang BlankOn.",
  installation_finish : "Pemasangan selesai.",
  installation_error_occured : "Terjadi galat saat pemasangan",
  please_take_look : "Silakan lihat di log pemasangan : /var/log/blankon-installer.log",
  installation : "Pemasangan",
  please_wait_system_scanned : "Sistem sedang dipindai...",
  please_choose_partition : "Silakan pilih partisi pada diska di bawah ini untuk memasang BlankOn atau gunakan pemartisi untuk kontrol lebih.",
  install_partition : "Tujuan pemasangan",
  installation_summary : "Ringkasan Pemasangan",
  install_summary_info : "Ini adalah ringkasan pemasangan. Lanjutkan jika Anda setuju. Setelah ini, Pemasang akan membuat perubahan pada sistem Anda dan Anda tidak dapat membatalkannya.",
  personalization  : "Personalisasi",
  please_enter_personalization : "Masukkan preferensi personal Anda di bawah ini ...",
  computer_name : "Nama komputer",
  full_name : "Nama",
  username : "Nama pengguna",
  password : "Kata sandi",
  repeat_password : "Ulangi kata sandi",
  automatically_login : "Masuk secara otomatis",
  enforced_password : "Gunakan kata sandi kuat",
  enforced_password_requirements : "Kata sandi Anda harus terdiri dari minimal 8 huruf, satu huruf besar dan satu angka.",
  please_fill_required_form : "Silakan melengkapi semua isian yang diperlukan.",
  next : "Lanjut",
  previous : "Kembali",
  continue_using_livecd : "Lanjut menggunakan sistem dalam moda live",
  install_blankon : "Pasang BlankOn",
  exit : "Keluar",
  install : "Pasang BlankOn",
  reboot : "Mula Ulang",
  timezone : "Zona Waktu",
  select_drive : "Pilih diska...",
  cancel : "Batal",
  apply : "Terapkan",
  use_as_swap : "gunakan sebagai Swap",
  used : "Sudah digunakan",
  too_small : "Terlalu kecil",
  free_space : "Ruang kosong",
  enter_advanced_mode : "Masuk ke moda mahir",
  you_are_choosing : "Anda memilih",
  to_be_installed_with : "untuk dipasang dengan BlankOn.",
  warning : "PERINGATAN",
  the_selected_partition_will_be_wiped_out : "Partisi terpilih akan dihapus. Partisi Swap akan dibuat jika tidak ada.",
  exit_advanced_mode : "Keluar dari moda mahir",
  are_you_sure_exit_advanced_mode : "Anda yakin ingin keluar dari moda mahir?",
  if_yes_any_step_will_be : "Jika iya, setiap langkah yang sudah dipilih di PartoEdi akan dibatalkan.",
  no : "Tidak",
  yes : "Ya",
  should_one_partition_as_root : "Harus ada satu partisi dengan sistem berkas root.",
  partition : "Partisi",
  file_system : "Sistem berkas",
  mount_point : "Kaitan",
  size : "Ukuran",
  new_partition : "Partisi Baru",
  unallocated : "Belum ditentukan",
  format_as_ext4 : "Format sebagai ext4",
  create : "Buat",
  delete : "Hapus",
  action : "Aksi",
  use_as_home : "Gunakan sebagai /home",
  will_be_ext4 : "Partisi ini akan diformat sebagai sistem berkas ext4.",
  will_be_swap : "Partisi ini akan diformat sebagai sistem berkas swap.",
  new_size : "Ukuran baru",
  partition_type : "Jenis Partisi",
  target_device : "Diska tujuan",
  target_partition : "Partisi tujuan",
  your_system_is_ready : "Sistem Anda sudah siap. Silakan memula ulang untuk masuk ke sistem Anda yang baru.",
  installing_filesystem : "Memasang sistem berkas",
  mounting_filesystem : "Mengkaitkan sistem berkas",
  mounting_home_filesystem : "Mengkaitkan sistem berkas /home",
  copying_filesystem : "Menyalin berkas",
  setting_up : "Menerapkan pengaturan awal",
  installing_grub : "Memasang GRUB",
  cleaning_up : "Merapikan sistem",
  create_partition : "Buat partisi",
  format_partition : "Format Partisi",
  partitioning_in_advancedMode : "Partisi dalam moda Mahir",
}
