var en = {
  welcome_to_program : "Welcome to BlankOn installation program.",
  installation_finish : "Installation Finish.",
  installation_error_occured : "Installation Error Occured.",
  please_take_look : "Please take a look at installion log : /var/log/blankon-installer.log",
  installation : "Installation",
  please_wait_system_scanned : "Please wait while your sistem is being scanned...",
  please_choose_partition : "Please choose the partition on device below which you would like to install BlankOn into or use advanced partitioning tool for more control.",
  install_partition : "Installation Target",
  installation_summary : "Installation Summary",
  install_summary_info : "This is our installation summary. Please proceed if you're agree. Beyond this point, the installer will make changes to your system and you can't go",
  personalization : "personalization",
  please_enter_personalization : "Please enter your personalization preference below...",
  computer_name : "Computer Name",
  your_name : "Your Name",
  username : "Username",
  password : "password",
  repeat_password : "Repeat Password",
  automatically_login : "Automatically login",
  enforced_password : "Enforce strong password",
  your_password_complexity : "Your password must contain at least 8 letters, a capital, and a numeric",
  please_fill_required_form : "Please fill all the required form.",
  next : "Next",
  previous : "Previous",
  continue_using_livecd : "Continue using live CD",
  install_blankon : "Install BlankOn",
  exit : "Exit",
  install : "Install",
  reboot : "Reboot",
  timezone : "TimeZone"

}

var id = {
  welcome_to_program : "Selamat datang di program pemasang BlankOn.",
  installation_finish : "Pemasangan selesai.",
  installation_error_occured : "Terjadi galat saat pemasangan",
  please_take_look : "Silakan lihat di log pemasangan : /var/log/blankon-installer.log",
  installation : "Pemasangan",
  please_wait_system_scanned : "Sistem sedang dipindai...",
  please_choose_partition : "Silakan pilih partisi pada diska di bawah ini untuk memasang BlankOn atau gunakan pemartisi untuk kontrol lebih.",
  install_partition : "Tujuan pemasangan",
  installation_summary : "Ringkasan Pemasangan",
  install_summary_info : "Ini adalah ringkasan pemasangan. Lanjutkan jika Anda setuju. Setelah ini, Pemasang akan membuat perubahan pada sistem Anda dan Anda tidak dapat membatalkannya",
  personalization  : "Personalisasi",
  please_enter_personalization : "Masukkan preferensi personalisasi Anda di bawah ini ...",
  computer_name : "Nama komputer",
  your_name : "Nama",
  username : "Nama pengguna",
  password : "Kata sandi",
  repeat_password : "Ulangi kata sandi",
  automatically_login : "Masuk secara otomatis",
  enforced_password : "Kata sandi yang kuat",
  your_password_complexity : "Kata sandi Anda harus terdiri dari minimal 8 huruf, satu huruf besar dan satu angka.",
  please_fill_required_form : "Silakan melengkapi semua isian yang diperlukan.",
  next : "Lanjut",
  previous : "Kembali",
  continue_using_livecd : "Lanjut menggunakan sistem dalam moda live",
  install_blankon : "Pasang BlankOn",
  exit : "Keluar",
  install : "Pasang BlankOn",
  reboot : "Mula Ulang",
  timezone : "Zona Waktu"
}
